// <auto-generated />
using System;
using System.Collections.Generic;
using ArcheryTracker.Logic.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ArcheryTracker.App.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211017035235_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ArcheryTracker.Logic.Models.Round", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<List<int>>("Scores")
                        .HasColumnType("integer[]");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("SessionId1")
                        .HasColumnType("text");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalShots")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId1");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("ArcheryTracker.Logic.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("AccuracyBullseye")
                        .HasColumnType("double precision");

                    b.Property<double>("AccuracyOnTarget")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageRoundScore")
                        .HasColumnType("double precision");

                    b.Property<int>("BestRoundScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("integer");

                    b.Property<int>("Range")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBullseye")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMisses")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOnTarget")
                        .HasColumnType("integer");

                    b.Property<int>("TotalShots")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ArcheryTracker.Logic.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArcheryTracker.Logic.Models.UserStats", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("OverallAccuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("OverallBullseyeAccuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("PreviousOverallAccuracy")
                        .HasColumnType("double precision");

                    b.Property<double>("ShotsPerSession")
                        .HasColumnType("double precision");

                    b.Property<int>("ShotsThisMonth")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBullseye")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOnTarget")
                        .HasColumnType("integer");

                    b.Property<int>("TotalShots")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserId1")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId1")
                        .IsUnique();

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("ArcheryTracker.Logic.Models.Round", b =>
                {
                    b.HasOne("ArcheryTracker.Logic.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.HasOne("ArcheryTracker.Logic.Models.Session", null)
                        .WithMany("Rounds")
                        .HasForeignKey("SessionId1");
                });

            modelBuilder.Entity("ArcheryTracker.Logic.Models.Session", b =>
                {
                    b.HasOne("ArcheryTracker.Logic.Models.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ArcheryTracker.Logic.Models.UserStats", b =>
                {
                    b.HasOne("ArcheryTracker.Logic.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ArcheryTracker.Logic.Models.UserStats", "UserId");

                    b.HasOne("ArcheryTracker.Logic.Models.User", null)
                        .WithOne("Stats")
                        .HasForeignKey("ArcheryTracker.Logic.Models.UserStats", "UserId1");
                });

            modelBuilder.Entity("ArcheryTracker.Logic.Models.Session", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("ArcheryTracker.Logic.Models.User", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
